server/utils/commons.js
在1.3.2版本上开发时，开发环境为`127.0.0.1:3000`可正常获取mock接口数据，但是`localhost:3000`下不支持.调整了下，在1.3.2版本上测试可以正常访问mock接口
=> fix: support develop locahost:3000

server/controllers/project.js, server/models/project.js, static/doc/static/server/controllers/project.js.html
查看官方1.3.4没有更新这个bug:
在一个group创建项目的时候，如创建的项目名同其他group下已经存在的项目name相同，会报错:项目名重复。
个人理解：每一个group应该是单独的一个项目集合，group之间不应该有关联，包括项目名。
=> fix: 实现不同group可以创建相同的项目名

server/install.js, server/utils/db.js
修复mongodb帐号密码配置错误时引发的错误
error: MongoError: Authentication failed.mongodb connect error
(node:69168) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: Authentication failed.
(node:69168) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
=> fix: Unhandled promise rejection

client/components/AceEditor/mockEditor.js
处理响应体既不是string也不object的情况时handleData返回的数据就成为了undefined
=> fix: handleData return undefined.

server/utils/db.js
fix: mongoose warning 'Error:  (node:3819) DeprecationWarning: collection.ensureIndex is deprecated. Use createIndexes instead'
=> fix: mongoose warning 'Error:  (node:3819) DeprecationWarning: collection.ensureIndex is deprecated. Use createIndexes instead'

common/config.js, exts/yapi-plugin-export-swagger2-data/client.js, exts/yapi-plugin-export-swagger2-data/controller.js, exts/yapi-plugin-export-swagger2-data/index.js, exts/yapi-plugin-export-swagger2-data/server.js
添加了新的插件yapi-plugin-export-swagger2-data。实现了导出Swagger格式的Json的功能。实现了大部分接口信息的转换，生成的json方便用于Swagger-Editor。
目前存在的问题：
1. 部分属性，不能直接对应OpenAPI的规范，故不能直接转换，如：tag
2. 导出格式目前是基于OpenAPI 2.0， 并非最新的V3.0
3. 暂时导出Json而不是Yaml （如果转换需要额外引入第三方组件，而Swagger-Editor可以直接使用Json，也能直接在线转换为yaml格式）
=> feat:  export data as swagger json #714 #724

common/postmanLib.js
yapi服务端运行时， 有302跳转， 无法获取302跳转前的headers， 比如登录请求`/signin` 返回一个302请求， 登录请求成功的cookie会在这个请求的头部, 但是axios默认maxRedirects为5， 会自动跟随302重新定向到新页面，而新页面没有请求成功的这个cookie，从而无法获取这个cookie。 现在这里被macRedirects改为0， 让其不跟随重定向， 就可以正常获取这个cookie。 请求合并， 谢谢。
=> 修复无法获取请求302 跳转前的 headers

server/controllers/open.js
curl http://127.0.0.1:3000/api/open/import_data -H 'Content-Type: application/x-www-form-urlencoded' -d 'type=swagger&dataSync=merge&token=524aa51f192db5158959e0ed9c2512386c1f257407207dbb4d9b4b267ffc5daa&json=http%3A%2F%2F172.18.8.5%3A13088%2Fswagger%2Fdocs%2Fv1'
=> /api/open/import_data 导入数据接口，增加url支持,比如从swagger的url获取完整json数据进行导入，调用示例：

ykit.config.js
路径分隔符 在Windows 和 Linux 不相同，
linux文件路径分隔符为 __"/"__ ，windows的文件路径分隔符为 __"\\"__ 
``` js
path.join('foo', 'bar');
// 在 OSX 和 Linux 得到 'foo/bar'
// 在 Windows 得到 'foo\\bar'
```
=>  node path 兼容windows

common/markdown.js
**路径参数**
| 参数名称 | 示例  | 备注  |
| ------------ | ------------ | ------------ | ------------ | ------------ |
| id |   |  角色id |
**路径参数**
| 参数名称 | 示例  | 备注  |
| ------------ | ------------ | ------------ |
| id |   |  角色id |
=> fix:导出markdown文档路径参数在某些编辑器下显示错位的问题

common/markdown.js
目前数据导出的时候，直接mock的数据会显示为undefined: @ip这种，默认没有接口描述也会显示为undefined
=>  fix: 解决md显示直接mock数据和接口描述为undefined的问题

client/containers/Project/Interface/InterfaceList/InterfaceEditForm.js
-  在编辑接口-请求参数设置的时候，如果删除了全部的参数再次点击批量添加的时候会报错
-  批量添加的时候，很多时候我们也需要批量添加备注信息。如果参数名和例子能支持批量导入，备注缺不支持，在操作上会有些不便捷。因此添加了支持批量导入备注的功能。需要注意的地方就是例子的数据不能含有英文冒号，因为分隔符就是英文冒号，否则会造成数据丢失
=> fixed bugs 编辑接口的时候删除请求参数再次点批量添加会报错

client/components/Postman/Postman.js, client/containers/Project/Interface/InterfaceCol/InterfaceColContent.js, client/containers/Project/Setting/ProjectInterfaceSync/index.js, client/containers/Project/Setting/Setting.js, client/reducer/modules/project.js, common/postmanLib.js, package.json, server/app.js, server/controllers/open.js, server/controllers/project.js, server/models/project.js, server/router.js, server/utils/interfaceSyncUtils.js
新增代码让pre request和pre reponseo脚本能够获取和设置到环境配置中global的值等
比如我配置如下环境配置
然后我在pre-request中修改getTokenTime,通过`context.envParams.环境名称.global.属性名`进行获取和设置环境变量值
比如我的pre-request代码如下,get_token是我的环境变量名,getTokenTime是我的变量名
```
context.envParams.get_token.global.getTokenTime = new Date().getTime();
```
执行任意接口运行后,可以看到结果如下,getTokenTime的值进行了修改,证明pre-request脚本中修改有效,并且pre request script中修改的值在pre response script就能获取到
=> 让pre request和pre response脚本中可以获取和设置环境变量的global,新增swagger接口自动同步功能

client/containers/Project/Interface/InterfaceList/InterfaceList.js, client/reducer/modules/interface.js, package.json, server/controllers/interface.js, server/models/interface.js
将接口过滤放在服务端,效果如下:
fix #1221
fix #1052
=> opti: filtering interface on the server instead of client

exts/yapi-plugin-swagger-auto-sync/controller/syncController.js
修改Swagger自动同步信息时检查对项目有edit权限
fix #1249
=> fix: 修改Swagger自动同步信息时检查权限

client/components/TimeLine/TimeLine.js, exts/yapi-plugin-import-swagger/run.js
通过插件导入的数据，很多情况下都会存在少量的格式不规范问题
https://github.com/YMFE/yapi/issues/1180
=> 当传入数据格式的 method 不规范时，容易导致获取对象为空，出现异常导致动态页面无法打开

package.json
此问题会导致 swagger schema json 引入 url 对象时报错 reference not found
=> 解决 https://github.com/json-schema-faker/json-schema-faker/issues/453 问题

server/controllers/interface.js
当传了required参数时，由于三目运算符属性写错，导致alwaysFakeOptionals属性设置错误
=> fix: schema2json传required参数时，导致faker失败

config_example.json, server/app.js
自动化测试时服务端测试node默认2分钟没有返回就直接断掉连接，可以手动设置一个超时时间。
#1455
#705
=> 自动化测试时服务端测试node默认2分钟没有返回就直接断掉连接，可以手动设置一个超时时间。

exts/yapi-plugin-advanced-mock/server.js
弃用自定义且校验逻辑有问题的 isDeepMatch 方法，使用 lodash 的 isEqual 方法比较参数
=> fix: use lodash compare json other than lib isDeepMatch

exts/yapi-plugin-import-swagger/run.js
修复swaggerjson导入yapi中时，formData格式的example属性在yapi页面示例中不显示问题
=> fix(swaggerjson中formData格式example属性在yapi页面不显示)

exts/yapi-plugin-swagger-auto-sync/interfaceSyncUtils.js
1.接口无更新,不保存日志
2.syncInterface 接口无更新,修改sync_model的属性失败
=> swagger定时同步

client/containers/Project/Interface/InterfaceList/InterfaceEditForm.js
- 使用 `substring`来分割参数,防止参数值中包含`:`时被截断
fix #1493 
---
这里有个问题是如下这种情况:
```
aaa
bbb:
ccc:ddd
```
这里的`aaa`该不该当做一个参数录入?
=> fix: use `sub` instead of `split` to parse parameters

common/markdown.js
如图所示我在三个文件夹分类下都有叫列表的接口，导出的菜单都定位到了技术服务费的列表接口位置。
debug后发现html是markdown转的，转的时候接口名的div id就是接口名，相同的接口名导致div id重复。故我在将div id设为了“接口名+catid”的格式，避免出现相同div id
=> fix: 修复导出html接口文档时，不同目录下有相同接口名导致的接口错位问题

common/markdown.js
Co-authored-by: wangxl <wangxl@onton.net>
=> fix: 修复导出html接口文档时，不同目录下有相同接口名导致的接口错位问题 (#2270)

package.json
修复安装时抛出`TypeError: jsf.extend is not a function`的异常
https://github.com/YMFE/yapi/issues/2226
https://github.com/YMFE/yapi/issues/2228
=> fix: fixed install error

client/reducer/modules/project.js
已测试通过，由于数据导入和定时同步都是调用的`handleSwaggerUrlData`方法，所以这两个点都可以正常使用了。
相关issue：
- https://github.com/YMFE/yapi/issues/2026
- https://github.com/YMFE/yapi/issues/1371
=> 修复swagger url导入不支持中文的问题

client/containers/Project/Project.js
fix `Uncaught TypeError: Cannot convert undefined or null to object` while the curProject is null.
=> fix: check curProject before call Object.keys

server/controllers/project.js, server/models/follow.js
- delete follow info while delete project
- fix #1689
=> fix: delete follow info while delete project

client/containers/Project/Interface/InterfaceCol/InterfaceColContent.js, client/containers/Project/Interface/InterfaceCol/InterfaceColMenu.js
=> Fix interfaceCol 报错'col_id不能为空'
