exts/yapi-plugin-import-swagger/client.js

responses中成功的状态码不仅仅只有200，可能会是其它的，比如201

2xx的http statusCode都应该被处理

---

.npmrc

添加.npmrc文件

---

docs/documents/project.md

响应数据变量应该是responseData，而不是responseBody。使用responseBody，运行接口会报错，因为变量名错误。

docs: 请求配置返回数据示例中 responseBody -> responseData

---

client/containers/Project/Interface/InterfaceCol/InterfaceColContent.js
client/containers/Project/Setting/ProjectData/ProjectData.js

1.修复a标签的_blank产生的安全问题
https://mathiasbynens.github.io/rel-noopener/
2.统一项目中a标签的顺序_target, rel, href 的方式

fix: link of safe && style

---

client/containers/User/Profile.js

fix: 处理 Profile.js 中 missing in props validation 报错

---

docs/documents/plugin-list.md

添加钉钉机器人推送插件

---

docs/documents/plugin-list.md

[add]新增导出docx文档插件

---

package.json

dependencies 和 devDependencies 中 moment 重复

重复的 moment 依赖，导致安装时报错

---

README.md

fix typo - oauth

---

exts/yapi-plugin-import-swagger/run.js
package.json

将OpenAPI比较版本由等值比较，改为大于等于
[OpenAPI current-version](https://github.com/OAI/OpenAPI-Specification#current-version---302)

修改OpenAPI比较版本方法

---

package.json

license should be a valid SPDX license expression => https://spdx.org/licenses/

解决 license should be a valid SPDX license expression 报错

---

README.md

提交了docker安装yapi的文件和环境。仅仅需要 clone -> build -> run

添加docker安装yapi 其他办法

---

server/controllers/base.js

正在进行 `yapi-to-typescript` v1 版本开发的前期调研，需要这个接口。
详细：https://github.com/fjc0k/yapi-to-typescript/issues/8

feat: 将数据导出接口加入 openapi

---

docs/documents/project.md

新增Swagger自动同步和请求脚本获取变量的功能说明

---

client/containers/Project/Setting/ProjectInterfaceSync/index.js
server/controllers/open.js

修复服务端测试获取环境配置global变量的bug

---

common/postmanLib.js
server/controllers/open.js

fix: 修复服务端测试pre-request和pre-response脚本获取不到环境配置中的global的问题
本次验证了手动测试,自动化测试,服务端测试均可成功获取和设置到环境配置中的global变量的值

fix: 修复服务端测试pre-request和pre-response脚本获取不到环境配置中的global的问题

---

server/utils/storage.js

bugfix: save storage logic error

---

client/components/Header/Header.scss

Fixed Avatar Position Bug

---

README.md

docker-compose 一键部署

---

client/components/Header/Search/Search.js
server/models/interface.js

搜索接口路径应该是个很实用的需求
实现方式上有点简单粗暴，不妥的话可以探讨下

feat: 全局搜索模块支持搜索接口路径

---

server/controllers/interface.js

不影响现有功能，使得以下开放接口都可以支持tag参数
- /api/interface/add [新增接口]
- /api/interface/save [保存接口]
- /api/interface/up [更新接口]
fix #1206

opti: tag of interface could be addAndUpCommonField

---

README.md

- 提供我正在使用并持续开发的IDEA插件
- 我有认真尝试使用并阅读YapiIdeaUploadPlugin的源码,觉得easy-yapi可能可以满足另一部分开发者的需求
- 支持开箱零配置即用,亦提供了丰富的自定义配置,以满足不同的开发者的自身业务需求
- 我将跟进实现对yapi最新功能的支持
- 已实现的支持如下:
- api的基础解析
- 从IDEA api相关代码处发起对api的请求
- 对yapi的特性支持如下
- yapi的tag
- yapi的mock配置
- 解析{@link }、@see 、@deprecated 等注释为yapi对应链接
- 提供图形化界面,可以使用拖拽的方式将项目中的api导入到yapi
- 如果有小伙伴需要，下一步计划,准备完成v1.0.0的开发，着手对其他语言框架的支持:node、python
- 希望可以帮助yapi走的更远!
- Feel free to close this PR!

feat: another plugin to upload API from code 'IDEA/Spring' to yapi

---

server/controllers/project.js

close: https://github.com/YMFE/yapi/issues/1253

fix: 优化插件【Swagger 自动同步】在添加地址时的服务端校验行为

---

client/components/Postman/Postman.js
client/components/Postman/Postman.scss

close: https://github.com/YMFE/yapi/issues/881, https://github.com/YMFE/yapi/issues/1282
实际效果如图：

feat: 运行接口请求时支持自动预览HTML

---

README.md

add pm2 yapi service manage

---

exts/yapi-plugin-export-swagger2-data/controller.js

修复导出的swaggerJson，POST表单的consumes参数错误；
修复导出的swaggerJson，请求参数是否必须无效的错误

修复导出的swaggerJson，POST表单的consumes参数错误；修复导出的swaggerJson，请求参数是否必须无效的错误

---

client/containers/Project/Interface/InterfaceList/InterfaceEditForm.js
exts/yapi-plugin-import-yapi-json/client.js
server/controllers/interface.js

Feel free to close this PR if it's not a fault

chore: fix typo

---

client/containers/Project/Interface/InterfaceList/InterfaceEditForm.js

fix: handle null value in  handleBulk

---

client/components/Postman/Postman.js
client/containers/Project/Interface/InterfaceCol/InterfaceColContent.js
client/plugin.js

feat: add hook request

---

README.md

《Api Generator》是一款可自动上传YApi接口的IDEA插件，大幅提升开发效率，是YApi好搭档。

添加接口文档自动生成插件

---

server/controllers/interface.js

support switch_notice for openapi ` /api/interface/save`

feat: support switch_notice for /interface/save

---

server/utils/ldap.js

修改ldap filter的匹配规则，使其可以匹配&和|操作符

修改ldap filter的匹配规则，使其可以匹配&和|操作符

---

exts/yapi-plugin-advanced-mock/server.js

Revert "fix: use lodash compare json other than lib isDeepMatch"

---

README.md

docker-yapi更新为docker-compose方式

---

exts/yapi-plugin-advanced-mock/server.js
package.json
server/utils/commons.js
server/utils/sandbox.js

fix: fixed_sandbox_bug

---

README.md

开发了一个Idea插件，支持一键生成api接口文档上传到Yapi: https://github.com/jetplugins/yapix

doc: 增加Yapi X文档生成插件链接

---

README.md

doc: Add Megvii.com to readme.md

---

client/containers/Project/Setting/ProjectData/ProjectData.scss

fix the ProjectData style disorder,修复样式错乱问题

fix: fix the ProjectData style disorder,修复样式错乱问题

---

client/containers/Project/Interface/InterfaceList/View.js

feat: 屏幕宽度小的情况下，鼠标hover接口名称能显示全部

---

common/schema-transformTo-table.js

导入openapi json的时候字段备注加入title展示

feat: 为字段添加title描述

---

client/components/Notify/Notify.js
package.json

fix: 修复沙盒越权

---

common/postmanLib.js
package-lock.json
package.json
server/controllers/base.js
server/middleware/mockServer.js

v1.11.0 之后 如下脚本功能关闭,如需打开,请联系管理员添加. 在 db, mail 同级配置 scriptEnable: true, 并重启服务 即可

Bugfix 2022 11 01 
